### ISSUE TITLE
右に寄ってるのを中央にする

### ISSUE THREAD

**Issue by ndxbn** [naporin0624/sana-button-front-end#37]
再生・停止を押すときに、手のひらで謝操作しそう。
![2020-03-07_10-10-30_000409](https://user-images.githubusercontent.com/2140131/76133525-e5af9000-605b-11ea-90b7-c868a00dd17b.png)

多分、column-end になってるからなのかなぁと思うのだけれど、わからん

**Comment by euxn23** [comment]
おそらくこれで大丈夫かと！
https://github.com/naporin0624/sana-button-front-end/commit/698473508c1de64c4d0a9250b2827b8df4d0ec53
